/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** True when every virtual-key code in `keys` is currently held down. */
export declare function areKeysDown(keys: Array<number>): boolean

/** The largest visible, unowned top-level window of the process, if any. */
export declare function findMainWindow(pid: number): number | null

/** Snapshot of running processes. Cheap enough to call every couple of seconds. */
export declare function listProcesses(): Array<ProcessInfo>

export interface ProcessInfo {
  pid: number
  /** Executable file name, e.g. "Risk of Rain 2.exe". */
  name: string
}

/**
 * Reads text from regions of a window with Windows OCR, off the main thread.
 * Resolves to one list of text lines per region.
 */
export declare function readScreenText(hwnd: number, regions: Array<ScreenRegion>, language?: string | undefined | null): Promise<unknown>

/** Rectangle in physical screen pixels. */
export interface Rect {
  x: number
  y: number
  width: number
  height: number
}

/** Part of a window's client area, as fractions of its width and height (0..1). */
export interface ScreenRegion {
  x: number
  y: number
  width: number
  height: number
  /** Enlargement before OCR; small HUD text reads better at 2x (the default). */
  scale?: number
}

/**
 * Start tracking one window. Replaces any tracker that is already running.
 * The callback first receives an "initial" snapshot, then one per relevant change.
 */
export declare function startWindowTracking(hwnd: number, callback: ((arg: WindowSnapshot) => void)): void

export declare function stopWindowTracking(): void

/** Snapshot of the tracked window. Every event carries the full state, so consumers can stay stateless. */
export interface WindowSnapshot {
  /** What triggered this snapshot: "initial", "foreground", "move", "minimize", "restore" or "destroy". */
  reason: string
  /** Handle of the current foreground window. */
  foreground: number
  targetFocused: boolean
  minimized: boolean
  /** Client area of the tracked window. None while minimized or after it was destroyed. */
  bounds?: Rect
}
